### ISSUE TITLE
(error: [object DOMError])

### ISSUE THREAD

**Issue by madboycash** [theopolisme/location-history-visualizer#19]
Something went wrong reading your JSON file. Ensure you're uploading a "direct-from-Google" JSON file and try again, or create an issue on GitHub if the problem persists. (error: [object DOMError])

I downloaded the locationhistory JSON file twice and both times I got this error.

**Comment by ymongo** [comment]
Hello there, 

I have the same issue! JSON file downloaded from google, and I have the same error message. Is this tool still updated?

**Comment by PJRay** [comment]
I'm getting the same - my json is fairly large (343 MB), but still... is anyone looking at this?

I was considering getting the pro/paid version, but I will definitely not do that before this issue is fixed.

**Comment by theopolisme** [comment]
Hi Pia, the Pro version does not have the issue; it runs as a full desktop
app and is immune to this issue.

The heatmap website, however, is subject to the memory restrictions of the
web browser, and thus still runs into this memory allocation issue.

**Comment by ymongo** [comment]
Late reply after closed case: At that time I hadn't thought about it, but I crashed it I was using the location history visualizer with firefox... I recently tried with Chrome: it worked fine!
