### ISSUE TITLE
Show date

### ISSUE THREAD

**Issue by ajs124** [theopolisme/location-history-visualizer#8]
The json file contains the date and I think it would be nice if it was visualized somehow.

**Comment by pierlauro** [comment]
As you can see in my [last pull request](https://github.com/theopolisme/location-history-visualizer/pull/11), now you can choose to show only the location history between two dates.

Work in progress for a simple and intuitive way to show the timestamp without immersing the map.

**Comment by delf1980** [comment]
Please add a possibility to show the actual timestamp on each circle. Maybe in a tooltip if there are more than one timestamp?

**Comment by pierlauro** [comment]
It will be done as soon as I will have time. Actually I think this project is dead since the pull requests are pending since 2015. I will continue on my own fork when I'll have time.
